const D_IFTD_LAT = {
    'Ā': 'AA',
    'Ē': 'EE',
    'Ī': 'YI',
    'Ō': 'OO',
    'Š': 'SH',
    'Č': 'CH',
    'Ž': 'ZH',
    'Ṣ': 'TH',
    'Ḥ': 'HK',
    'Ç': 'TS',
    'Ñ': 'NY',
    'ā': 'aa',
    'ē': 'ee',
    'ī': 'yi',
    'ō': 'oo',
    'š': 'sh',
    'č': 'ch',
    'ž': 'zh',
    'ṣ': 'th',
    'ḥ': 'hk',
    'ç': 'ts',
    'ñ': 'ny'
};
const IFTD_D_LAT = {
    'AA': 'Ā',
    'EE': 'Ē',
    'YI': 'Ī',
    'OO': 'Ō',
    'SH': 'Š',
    'CH': 'Č',
    'ZH': 'Ž',
    'TH': 'Ṣ',
    'HK': 'Ḥ',
    'TS': 'Ç',
    'NY': 'Ñ',
    'Aa': 'Ā',
    'Ee': 'Ē',
    'Yi': 'Ī',
    'Oo': 'Ō',
    'Sh': 'Š',
    'Ch': 'Č',
    'Zh': 'Ž',
    'Th': 'Ṣ',
    'Hk': 'Ḥ',
    'Ts': 'Ç',
    'Ny': 'Ñ',
    'aa': 'ā',
    'ee': 'ē',
    'yi': 'ī',
    'oo': 'ō',
    'sh': 'š',
    'ch': 'č',
    'zh': 'ž',
    'th': 'ṣ',
    'hk': 'ḥ',
    'ts': 'ç',
    'ny': 'ñ'
};
const LAT_ELL = {
    'Ṣ': 'Θ',
    'TH': 'Θ',
    'PS': 'Ψ',
    'Th': 'Θ',
    'Ps': 'Ψ',
    'ṣ': 'θ',
    'th': 'θ',
    'ps': 'ψ',
    'YA': 'JΑ',
    'YE': 'JΕ',
    'YI': 'JΙ',
    'YO': 'JΟ',
    'YU': 'JΥ',
    'Ya': 'Jα',
    'Ye': 'Jε',
    'Yi': 'Jι',
    'Yo': 'Jο',
    'Yu': 'Jυ',
    'ya': 'jα',
    'ye': 'jε',
    'yi': 'jι',
    'yo': 'jο',
    'yu': 'jυ',
    'SH': 'ΣΛ',
    'CH': 'CΛ',
    'ZH': 'ΖΛ',
    'Sh': 'Σλ',
    'Ch': 'Cλ',
    'Zh': 'Ζλ',
    'sh': 'σλ',
    'ch': 'cλ',
    'zh': 'ζλ',
    'KY': 'ΚΛ',
    'NY': 'ΝΛ',
    'HY': 'ΧΛ',
    'MY': 'ΜΛ',
    'RY': 'ΡΛ',
    'GY': 'ΓΛ',
    'DY': 'ΔΛ',
    'BY': 'ΒΛ',
    'PY': 'ΠΛ',
    'Ky': 'Κλ',
    'Ny': 'Νλ',
    'Hy': 'Χλ',
    'My': 'Μλ',
    'Ry': 'Ρλ',
    'Gy': 'Γλ',
    'Dy': 'Δλ',
    'By': 'Βλ',
    'Py': 'Πλ',
    'ky': 'κλ',
    'ny': 'νλ',
    'hy': 'χλ',
    'my': 'μλ',
    'ry': 'ρλ',
    'gy': 'γλ',
    'dy': 'δλ',
    'by': 'βλ',
    'py': 'πλ',
    'A': 'Α',
    'E': 'Ε',
    'I': 'Ι',
    'O': 'Ο',
    'U': 'Υ',
    'W': 'Υ',
    'Ā': 'Ᾱ',
    'Ē': 'Η',
    'Ī': 'Ῑ',
    'Ō': 'Ω',
    'K': 'Κ',
    'S': 'Σ',
    'T': 'Τ',
    'N': 'Ν',
    'H': 'Χ',
    'M': 'Μ',
    'R': 'Ρ',
    'G': 'Γ',
    'Z': 'Ζ',
    'D': 'Δ',
    'B': 'Β',
    'P': 'Π',
    'Y': 'J',
    'F': 'Φ',
    'X': 'Ξ',
    'a': 'α',
    'e': 'ε',
    'i': 'ι',
    'o': 'ο',
    'u': 'υ',
    'w': 'υ',
    'ā': 'ᾱ',
    'ē': 'η',
    'ī': 'ῑ',
    'ō': 'ω',
    'k': 'κ',
    's': 'σ',
    't': 'τ',
    'n': 'ν',
    'h': 'χ',
    'm': 'μ',
    'r': 'ρ',
    'g': 'γ',
    'z': 'ζ',
    'd': 'δ',
    'b': 'β',
    'p': 'π',
    'y': 'j',
    'f': 'φ',
    'x': 'ξ'
};
const ELL_LAT = {
    'QΥ': 'QU',
    'ΥΑ': 'WA',
    'ΥΕ': 'WE',
    'ΥΙ': 'WI',
    'ΥΟ': 'WO',
    'Qυ': 'Qu',
    'Υα': 'Wa',
    'Υε': 'We',
    'Υι': 'Wi',
    'Υο': 'Wo',
    'qυ': 'qu',
    'υα': 'wa',
    'υε': 'we',
    'υι': 'wi',
    'υο': 'wo',
    'ΣΛ': 'SH',
    'CΛ': 'CH',
    'ΖΛ': 'ZH',
    'Σλ': 'Sh',
    'Cλ': 'Ch',
    'Ζλ': 'Zh',
    'σλ': 'sh',
    'cλ': 'ch',
    'ζλ': 'zh',
    'Θ': 'TH',
    'Ψ': 'PS',
    'θ': 'th',
    'ψ': 'ps',
    'Α': 'A',
    'Ε': 'E',
    'Ι': 'I',
    'Ο': 'O',
    'Υ': 'U',
    'Ᾱ': 'Ā',
    'Η': 'Ē',
    'Ῑ': 'Ī',
    'Ω': 'Ō',
    'Κ': 'K',
    'Σ': 'S',
    'Τ': 'T',
    'Ν': 'N',
    'Χ': 'H',
    'Μ': 'M',
    'Ρ': 'R',
    'Γ': 'G',
    'Ζ': 'Z',
    'Δ': 'D',
    'Β': 'B',
    'Π': 'P',
    'Λ': 'Y',
    'Φ': 'F',
    'Ξ': 'X',
    'J': 'Y',
    'α': 'a',
    'ε': 'e',
    'ι': 'i',
    'ο': 'o',
    'υ': 'u',
    'ᾱ': 'ā',
    'η': 'ē',
    'ῑ': 'ī',
    'ω': 'ō',
    'κ': 'k',
    'σ': 's',
    'ς': 's',
    'τ': 't',
    'ν': 'n',
    'χ': 'h',
    'μ': 'm',
    'ρ': 'r',
    'γ': 'g',
    'ζ': 'z',
    'δ': 'd',
    'β': 'b',
    'π': 'p',
    'λ': 'y',
    'φ': 'f',
    'ξ': 'x',
    'j': 'y'
};
const LAT2_ELL2 = {
    'λι': 'jι'
};
function replaceRe(abotoka, list) {
    const rekrz = Object.keys(list).join('|');
    const re = new RegExp(rekrz, 'g');
    return abotoka.replace(re, match => list[match]);
}
function sigma(abotoka) {
    const re = new RegExp('σ(?![a-zA-Zα-ωΑ-ΩᾱῑçščžñᾹῙÇŠČŽÑāēīōĀĒĪŌ])', 'g');
    return abotoka.replace(re, match => 'ς');
}
export function hweSDL1(abotoka) {
    const abotok_LAT = replaceRe(abotoka, ELL_LAT);
    const abotok_SDL1 = replaceRe(abotok_LAT, IFTD_D_LAT);
    return abotok_SDL1;
}
export function hweSDL2(abotoka) {
    const abotok_LAT = replaceRe(abotoka, ELL_LAT);
    const abotok_SDL2 = replaceRe(abotok_LAT, D_IFTD_LAT);
    return abotok_SDL2;
}
export function hweSDE1(abotoka) {
    const abotok_SDL1 = hweSDL1(abotoka);
    const abotok_ELL = replaceRe(abotok_SDL1, LAT_ELL);
    return sigma(abotok_ELL);
}
export function hweSDE2(abotoka) {
    const abotok_SDL2 = hweSDL2(abotoka);
    const abotok_ELL = replaceRe(abotok_SDL2, LAT_ELL);
    return sigma(replaceRe(abotok_ELL, LAT2_ELL2));
}
